#pragma once
#include <stdint.h>

// Start BLE peripheral advertising + central scanning.
void ble_start(const char *nickname);

// Stop all BLE operations.
void ble_stop(void);

// Peripheral: send SDP chunks to all subscribed centrals.
// type: 'A' = answer
void ble_peripheral_send_sdp(const char *sdp, char sdp_type);

// Central: send SDP chunks to a specific peripheral (by UUID string).
// type: 'O' = offer
void ble_central_send_sdp(const char *peer_uuid, const char *sdp, char sdp_type);

// DataChar (BD9E0004): send raw bdpeer frame data (type byte 'D').
void ble_peripheral_send_data_to(const char *central_uuid, const uint8_t *data, int len);
void ble_central_send_data(const char *peripheral_uuid, const uint8_t *data, int len);

// ── Callbacks implemented in Go (generated via //export in ble_darwin.go) ────
// Declarations are auto-generated by cgo — do NOT redeclare them here.
// go_ble_peer_found, go_ble_sdp_received, go_ble_central_subscribed, go_ble_data_received
